### ISSUE TITLE
Add an on/off switch

### ISSUE THREAD

**Issue by rstacruz** [ubenzer/metalsmith-uglifyjs#14]
it'd be nice to have a way to toggle its uglifying behavior.

- If `active: true`, then it will work as usual.
- If `active: false`, it'll simply copy over the files unharmed (ie, like `cp app.js app.min.js`).

This allows you to turn compression off conditionally via `NODE_ENV`:

```js
var isProduction = process.env.NODE_ENV === 'production'

Metalsmith(__dirname)
  .use(require('metalsmith-uglifyjs')({
    active: isProduction,
    uglifyOptions: { mangle: true, compress: { warnings: false }}
  })
```

**Comment by ubenzer** [comment]
Hi @rstacruz sounds good to me. 👍 

Are you willing to open a PR for this?

**Comment by ubenzer** [comment]
Implemented.
